### ISSUE TITLE
unable to run python script

### ISSUE THREAD

**Issue by vass7** [ThomasVuNguyen/chatGPT-Voice-Assistant#4]
Hey im pretty new to coding and stuff. I have a problem when trying to run the python script. When trying to run Python3 gpt.py is says 

"Traceback (most recent call last):
File "/home/vass7/gpt.py", line 2, in <module>
import openai
Modulenotfounderror: No module named "openai"

I don't understand how to fix this, i have checked the code several times and tried to make new ones but i still get the same problem.

**Comment by ThomasVuNguyen** [comment]
Have you installed the openai package?

**Comment by Saamsundar** [comment]
I am also experiencing the same problem when try to run the program in my raspberry pi 4. I have already installed all the necessary modules including openai. pls give me a solution as i am new to coding.

**Comment by ThomasVuNguyen** [comment]
Did you use pip3 to install the modules & python3 to run the python script?
Maybe try python2 also.

Let me know if there's still problems

**Comment by Saamsundar** [comment]
Thank you for your immediate response I will contact you if there are any issues

**Comment by ThomasVuNguyen** [comment]
Certainly! Happy to help
